### ISSUE TITLE
最后一步填完两步验证码报错

### ISSUE THREAD

**Issue by WoodC2011** [gqbre/emby-server-checkin#4]
Traceback (most recent call last):
  File "/app/cm.py", line 50, in <module>
    tg.login()
  File "/usr/local/lib/python3.10/site-packages/telegram/client.py", line 718, in login
    self.authorization_state = self._wait_authorization_result(result)
  File "/usr/local/lib/python3.10/site-packages/telegram/client.py", line 646, in _wait_authorization_result
    result.wait(raise_exc=True)
  File "/usr/local/lib/python3.10/site-packages/telegram/utils.py", line 45, in wait
    raise RuntimeError(f'Telegram error: {self.error_info}')
RuntimeError: Telegram error: {'@type': 'error', 'code': 400, 'message': 'PHONE_CODE_INVALID', '@extra': {'request_id': 'updateAuthorizationState'}}

**Comment by gqbre** [comment]
电话号码试试去掉 + 号：8613000000000

**Comment by WoodC2011** [comment]
我号码是+1的，我填的是+1xxxxxxx这样的

docker run -d --name emby-server-checkin -e api_id="xxxxxxx" -e api_hash="xxxxxxxxxxxxxxxxxx" -e phone="+1xxxxxxxx" gqbre/emby-server-checkin

**Comment by gqbre** [comment]
我就是 +1 的，我直接是 iOS TG 客户端设置里长按手机号复制的（包含多处空格）直接使用试试；再不行就检查一下 API 申请的问题，只想到这些了
