### ISSUE TITLE
手动部署，运行时报错：Failed to parse JSON object as TDLib request: Can\'t parse "None" as an integer

### ISSUE THREAD

**Issue by Nigel-NI** [gqbre/emby-server-checkin#5]
按照“手动挡”部署方式，操作到0x03步时，程序报错，内容如下：
```
Traceback (most recent call last):
  File "/root/emby-server-checkin/cm.py", line 52, in <module>
    tg.login()
  File "/usr/local/lib/python3.9/dist-packages/telegram/client.py", line 718, in login
    self.authorization_state = self._wait_authorization_result(result)
  File "/usr/local/lib/python3.9/dist-packages/telegram/client.py", line 646, in _wait_authorization_result
    result.wait(raise_exc=True)
  File "/usr/local/lib/python3.9/dist-packages/telegram/utils.py", line 45, in wait
    raise RuntimeError(f'Telegram error: {self.error_info}')
RuntimeError: Telegram error: {'@type': 'error', 'code': 400, 'message': 'Failed to parse JSON object as TDLib request: Can\'t parse "None" as an integer', '@extra': {'request_id': 'updateAuthorizationState'}}
```
在amd架构与arm架构的服务器上运行时均出现相同报错。0x02中提到的需要修改的地方均已做对应的修改，已执行`pip3 install -r requirements.txt`安装依赖且安装时无报错。
cm.py修改过的内容如下（隐私信息已做处理）：
```
tg_args = {
            'api_id': f"{os.getenv('28*******')}", # 填入 api id
            'api_hash': f"{os.getenv('e***********************************0')}", # 填入 api hash
            'phone': f"{os.getenv('+138*******0')}", # Telegram账号
            'database_encryption_key': 'passw0rd!',
            'files_directory': f"{os.getcwd()}/sessions", # 修改储存session文件位置，防止重启>           
            'library_path': f"{os.getcwd()}/libtdjson_amd64.so" # tdlib 的绝对路径
        }
```
测试环境：amd + Debian 12;  arm + Ubuntu 20.04

**Comment by gqbre** [comment]
https://github.com/gqbre/emby-server-checkin/issues/3#issuecomment-1534412962
